# Generated by Django 5.0.8 on 2024-08-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="admin",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="email",
            field=models.EmailField(default="carlthronson@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
