# Generated by Django 5.0.8 on 2024-08-10 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_teammember_admin_teammember_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammember",
            old_name="admin",
            new_name="role",
        ),
    ]
