# Generated by Django 5.0.8 on 2024-08-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0003_rename_admin_teammember_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.BooleanField(default=False),
        ),
    ]
